{{- if .Values.lyrics.nginx.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.lyrics.namespace }}
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        server_name localhost;
        include /etc/nginx/mime.types;

        location / {
          root /usr/share/nginx/html/;
          try_files $uri $uri/ @server;

          add_header whoami I-am-static-files;
        }

        location @server {
          proxy_pass http://lyrics-app:8000;

          proxy_set_header Host "localhost";
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          add_header whoami I-am-app;
        }
      }
    }
{{- end }}
